# Generated by Django 4.2.13 on 2024-05-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "name",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
