# Generated by Django 4.2.13 on 2024-05-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="current_points",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "name",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
                ("desired_table_size", models.IntegerField(default=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("s", "started"),
                            ("wr", "waiting_round"),
                            ("ar", "active_round"),
                            ("f", "finished"),
                        ],
                        default="s",
                        max_length=60,
                    ),
                ),
                ("players", models.ManyToManyField(to="main.player")),
            ],
        ),
    ]
