# Generated by Django 4.2.13 on 2024-06-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_player_current_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="current_round",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("s", "started"), ("f", "finished")],
                        default="s",
                        max_length=60,
                    ),
                ),
                ("players", models.ManyToManyField(to="main.player")),
            ],
        ),
    ]
