# Generated by Django 4.2.13 on 2024-06-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_tournament_current_round_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("s", "started"), ("f", "finished")],
                        default="s",
                        max_length=60,
                    ),
                ),
                ("players", models.ManyToManyField(to="main.player")),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="round",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="main.round"
            ),
            preserve_default=False,
        ),
    ]
